-- MySQL Script generated by MySQL Workbench
-- sex 10 fev 2023 14:06:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotelcnp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelcnp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelcnp` DEFAULT CHARACTER SET utf8 ;
USE `hotelcnp` ;

-- -----------------------------------------------------
-- Table `hotelcnp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(45) NOT NULL,
  `cpfUsuario` VARCHAR(45) NOT NULL,
  `endUsuario` VARCHAR(45) NOT NULL,
  `senhaUsuario` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  `statusUsuario` VARCHAR(45) NOT NULL,
  `telefoneUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `cpfUsuario_UNIQUE` (`cpfUsuario` ASC) VISIBLE,
  UNIQUE INDEX `emailUsuario_UNIQUE` (`emailUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelcnp`.`acomodacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`acomodacoes` (
  `idAcomodacao` INT NOT NULL AUTO_INCREMENT,
  `nomeAcomodacao` VARCHAR(45) NOT NULL,
  `valorAcomodacao` DOUBLE NOT NULL,
  `numeroAcomodacao` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idAcomodacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelcnp`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`Reservas` (
  `idReservas` INT NOT NULL AUTO_INCREMENT,
  `dataReserva` DATE NOT NULL,
  `dataEntradaReserva` DATE NOT NULL,
  `dataSaidaReserva` DATE NOT NULL,
  `valorReserva` DOUBLE NOT NULL,
  `qtdHospedesReserva` INT NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  `acomodacoes_idAcomodacao` INT NOT NULL,
  PRIMARY KEY (`idReservas`),
  INDEX `fk_Reservas_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Reservas_acomodacoes1_idx` (`acomodacoes_idAcomodacao` ASC) VISIBLE,
  CONSTRAINT `fk_Reservas_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `hotelcnp`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_acomodacoes1`
    FOREIGN KEY (`acomodacoes_idAcomodacao`)
    REFERENCES `hotelcnp`.`acomodacoes` (`idAcomodacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelcnp`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`servicos` (
  `idServicos` INT NOT NULL AUTO_INCREMENT,
  `nomeServico` VARCHAR(45) NOT NULL,
  `valorServico` DOUBLE NOT NULL,
  PRIMARY KEY (`idServicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelcnp`.`Reservas_has_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`Reservas_has_servicos` (
  `Reservas_idReservas` INT NOT NULL,
  `servicos_idservicos` INT NOT NULL,
  PRIMARY KEY (`Reservas_idReservas`, `servicos_idservicos`),
  INDEX `fk_Reservas_has_servicos_servicos1_idx` (`servicos_idservicos` ASC) VISIBLE,
  INDEX `fk_Reservas_has_servicos_Reservas1_idx` (`Reservas_idReservas` ASC) VISIBLE,
  CONSTRAINT `fk_Reservas_has_servicos_Reservas1`
    FOREIGN KEY (`Reservas_idReservas`)
    REFERENCES `hotelcnp`.`Reservas` (`idReservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_has_servicos_servicos1`
    FOREIGN KEY (`servicos_idservicos`)
    REFERENCES `hotelcnp`.`servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelcnp`.`localConsumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`localConsumo` (
  `idLocalConsumo` INT NOT NULL AUTO_INCREMENT,
  `nomeLocalConsumo` VARCHAR(45) NOT NULL,
  `acomodacoes_idAcomodacao` INT NOT NULL,
  PRIMARY KEY (`idLocalConsumo`),
  UNIQUE INDEX `nomeLocalConsumo_UNIQUE` (`nomeLocalConsumo` ASC) VISIBLE,
  INDEX `fk_localConsumo_acomodacoes1_idx` (`acomodacoes_idAcomodacao` ASC) VISIBLE,
  CONSTRAINT `fk_localConsumo_acomodacoes1`
    FOREIGN KEY (`acomodacoes_idAcomodacao`)
    REFERENCES `hotelcnp`.`acomodacoes` (`idAcomodacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelcnp`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `nomeProdutos` VARCHAR(45) NOT NULL,
  `valorProdutos` DOUBLE NOT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelcnp`.`produtos_has_localConsumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`produtos_has_localConsumo` (
  `produtos_idprodutos` INT NOT NULL,
  `localConsumo_idLocalConsumo` INT NOT NULL,
  PRIMARY KEY (`produtos_idprodutos`, `localConsumo_idLocalConsumo`),
  INDEX `fk_produtos_has_localConsumo_localConsumo1_idx` (`localConsumo_idLocalConsumo` ASC) VISIBLE,
  INDEX `fk_produtos_has_localConsumo_produtos1_idx` (`produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_has_localConsumo_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `hotelcnp`.`produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_localConsumo_localConsumo1`
    FOREIGN KEY (`localConsumo_idLocalConsumo`)
    REFERENCES `hotelcnp`.`localConsumo` (`idLocalConsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelcnp`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`consumo` (
  `idConsumo` INT NOT NULL,
  `dataConsumo` DATE NOT NULL,
  `Reservas_idReservas` INT NOT NULL,
  `qtdConsumo` INT NOT NULL,
  `produtos_idprodutos` INT NOT NULL,
  `localConsumo_idLocalConsumo` INT NOT NULL,
  `servicos_idservicos` INT NOT NULL,
  PRIMARY KEY (`idConsumo`, `Reservas_idReservas`, `produtos_idprodutos`, `localConsumo_idLocalConsumo`),
  INDEX `fk_consumo_Reservas1_idx` (`Reservas_idReservas` ASC) VISIBLE,
  INDEX `fk_consumo_produtos1_idx` (`produtos_idprodutos` ASC) VISIBLE,
  INDEX `fk_consumo_localConsumo1_idx` (`localConsumo_idLocalConsumo` ASC) VISIBLE,
  INDEX `fk_consumo_servicos1_idx` (`servicos_idservicos` ASC) VISIBLE,
  CONSTRAINT `fk_consumo_Reservas1`
    FOREIGN KEY (`Reservas_idReservas`)
    REFERENCES `hotelcnp`.`Reservas` (`idReservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `hotelcnp`.`produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_localConsumo1`
    FOREIGN KEY (`localConsumo_idLocalConsumo`)
    REFERENCES `hotelcnp`.`localConsumo` (`idLocalConsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_servicos1`
    FOREIGN KEY (`servicos_idservicos`)
    REFERENCES `hotelcnp`.`servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `hotelcnp` ;

-- -----------------------------------------------------
-- Placeholder table for view `hotelcnp`.`servicosMostrar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotelcnp`.`servicosMostrar` (`nomeServico` INT, `valorServico` INT);

-- -----------------------------------------------------
-- View `hotelcnp`.`servicosMostrar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelcnp`.`servicosMostrar`;
USE `hotelcnp`;
CREATE  OR REPLACE VIEW `servicosMostrar` AS
SELECT
nomeServico,
valorServico
from servicos;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
